import React, { useState } from 'react';
import { Search, Sparkles, CheckCircle2, AlertTriangle, ArrowRight, X, ShieldCheck, Zap } from 'lucide-react';
import { motion } from 'framer-motion';
import { AnimatedSection } from './AnimatedSection';

interface AuditModalProps {
  isOpen: boolean;
  businessName: string;
  onClose: () => void;
  onConsult: () => void;
}

const AuditResultModal: React.FC<AuditModalProps> = ({
  isOpen,
  businessName,
  onClose,
  onConsult
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-md">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="relative w-full max-w-2xl bg-white rounded-3xl overflow-hidden shadow-2xl border border-slate-200 p-6 sm:p-8 space-y-6"
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-blue-100 text-blue-600 flex items-center justify-center font-bold">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs font-bold text-blue-600 uppercase tracking-widest">AI Audit Complete</div>
            <h3 className="text-2xl font-black text-slate-900">{businessName || 'Your Business'} Growth Score</h3>
          </div>
        </div>

        {/* Score Ring / Bar */}
        <div className="bg-slate-900 text-white p-6 rounded-2xl border border-slate-800 flex items-center justify-between gap-6">
          <div>
            <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">Overall Score</div>
            <div className="text-4xl font-black text-blue-400 mt-1">68 / 100</div>
            <p className="text-xs text-slate-300 mt-1">Moderate discovery. 3 critical growth leaks found.</p>
          </div>
          <div className="shrink-0 text-right">
            <span className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/30 text-xs font-bold">
              Action Required
            </span>
          </div>
        </div>

        {/* 3 Fixes Breakdown */}
        <div className="space-y-3">
          <div className="text-xs font-extrabold uppercase text-slate-400 tracking-wider">Top Recommended Growth Fixes</div>
          
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
            <div>
              <div className="text-sm font-bold text-slate-900">Slow WhatsApp Lead Follow-Up Delay</div>
              <p className="text-xs text-slate-600">Leads from Instagram DMs currently take &gt; 3 hours to be responded to. Automated bot flow can fix this instantly.</p>
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
            <div>
              <div className="text-sm font-bold text-slate-900">Inconsistent Reel Video Content</div>
              <p className="text-xs text-slate-600">Posting frequency is under 2 videos/week. High-retention 4K reels can double monthly reach.</p>
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-3">
            <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
            <div>
              <div className="text-sm font-bold text-slate-900">Good Google Business Listing Presence</div>
              <p className="text-xs text-slate-600">Google Maps profile active, but missing automated review response workflows.</p>
            </div>
          </div>
        </div>

        <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-slate-100">
          <div className="text-xs text-slate-500 flex items-center gap-1.5 font-medium">
            <ShieldCheck className="w-4 h-4 text-blue-600" />
            <span>Free report generated by Snackz AI Strategy Engine</span>
          </div>

          <button
            onClick={() => {
              onClose();
              onConsult();
            }}
            className="w-full sm:w-auto px-6 py-3 bg-gradient-to-r from-blue-600 to-cyan-600 text-white font-black text-sm rounded-xl shadow-lg shadow-blue-500/25 flex items-center justify-center gap-2 cursor-pointer"
          >
            <span>Fix These With Us</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

      </motion.div>
    </div>
  );
};

export const AuditGraderSection: React.FC<{ onConsult: () => void }> = ({ onConsult }) => {
  const [query, setQuery] = useState('');
  const [analyzing, setAnalyzing] = useState(false);
  const [showModal, setShowModal] = useState(false);

  const handleRunReport = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query) return;

    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
      setShowModal(true);
    }, 1800);
  };

  return (
    <section className="py-20 bg-[#040711] text-white relative overflow-hidden border-t border-slate-900">
      
      {/* Electric Blue Radial Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[400px] bg-gradient-to-r from-[#0047FF]/35 via-blue-600/20 to-transparent blur-3xl pointer-events-none rounded-full" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          
          <AnimatedSection direction="down">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-950/80 border border-blue-600/50 text-white text-xs font-grotesk font-extrabold uppercase tracking-widest">
              <Zap className="w-4 h-4 text-cyan-400 fill-[#FACC15]" />
              <span>FREE INSTANT AI GROWTH REPORT</span>
            </div>
          </AnimatedSection>

          <AnimatedSection direction="up" delay={0.1}>
            <h2 className="font-display text-3xl sm:text-4xl lg:text-5xl font-black text-white tracking-tight uppercase leading-tight">
              See where your brand is being missed online <span className="text-white">— in 30 seconds.</span>
            </h2>
          </AnimatedSection>

          <AnimatedSection direction="up" delay={0.2}>
            <p className="text-slate-300 text-base sm:text-lg max-w-2xl mx-auto font-medium">
              Enter your business or brand name below. Our AI strategy engine scores your social reach, lead response speed, and trust signals — then reveals your top fixes.
            </p>
          </AnimatedSection>

          {/* Interactive Search Bar Widget */}
          <AnimatedSection direction="scale" delay={0.3} className="pt-4">
            <form onSubmit={handleRunReport} className="relative max-w-2xl mx-auto flex flex-col sm:flex-row items-center gap-3 bg-white/10 backdrop-blur-xl p-2.5 rounded-3xl border border-white/20 shadow-2xl">
              <div className="relative w-full flex items-center">
                <Search className="w-5 h-5 text-blue-300 absolute left-4" />
                <input
                  type="text"
                  required
                  placeholder="Enter your business or brand name (e.g. EcoLuxe Spa)..."
                  value={query}
                  onChange={e => setQuery(e.target.value)}
                  className="w-full pl-12 pr-4 py-3.5 bg-transparent text-white placeholder-slate-400 font-semibold text-sm focus:outline-none"
                />
              </div>

              <button
                type="submit"
                disabled={analyzing}
                className="w-full sm:w-auto px-8 py-4 bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white font-extrabold text-sm rounded-2xl shadow-xl shadow-cyan-500/25 shrink-0 transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                {analyzing ? (
                  <>
                    <Sparkles className="w-5 h-5 animate-spin" />
                    <span>Analyzing...</span>
                  </>
                ) : (
                  <>
                    <span>Run Free Audit</span>
                    <ArrowRight className="w-5 h-5" />
                  </>
                )}
              </button>
            </form>

            <div className="pt-3 flex items-center justify-center gap-6 text-xs text-slate-400 font-medium">
              <span>✓ 100% Free Audit</span>
              <span>✓ No credit card needed</span>
              <span>✓ Instant 30s Score</span>
            </div>
          </AnimatedSection>

        </div>
      </div>

      <AuditResultModal
        isOpen={showModal}
        businessName={query}
        onClose={() => setShowModal(false)}
        onConsult={onConsult}
      />
    </section>
  );
};
